INSERT INTO `Categories` (`id`,`name`) VALUES
(1,'Action'),
(2,'Adventure'),
(3,'Animation'),
(4,'Biography'),
(5,'Comedy'),
(6,'Costume'),
(7,'Crime'),
(8,'Documentary'),
(9,'Drama'),
(10,'Family'),
(11,'Fantasy'),
(12,'History'),
(13,'Horror'),
(14,'Kungfu'),
(15,'Musical'),
(16,'Mystery'),
(17,'Mythological'),
(18,'Psychological'),
(19,'Romance'),
(20,'Sci-Fi'),
(21,'Sitcom'),
(22,'Sport'),
(23,'Thriller'),
(24,'TV Show'),
(25,'War');
